# fichier Dockerfile Production
FROM python:3.4

ENV PYTHONUNBUFFERED 1
ENV PYTHON_SETTINGS_MODULE=src.settings.prod

RUN mkdir /code
WORKDIR /code
ADD . /code/

RUN pip install -r requirements.txt \
    && python manage.py makemigrations \
    && python manage.py migrate \
    && python manage.py superuser \
    && python manage.py collectstatic --no-input

EXPOSE 8081:8000

CMD python manage.py runserver 0.0.0.0:8000 --settings=src.settings.prod



