version: '3'
services:

  web:
    build: .
    image: webapp:dev
    container_name: webapp-dev

    command: python manage.py runserver 0.0.0.0:8000 --settings=src.settings.local

    volumes:
      - .:/code
      - src-data:/code

    ports:
      - "8080:8000"

volumes:
    src-data:

