# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consommation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odometre', models.IntegerField()),
                ('quantite_essence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_conso', models.DateField(default=django.utils.timezone.now)),
                ('prix_litre', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_frais', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('annee', models.IntegerField()),
                ('petit_nom', models.CharField(max_length=20)),
                ('odometre_depart', models.IntegerField()),
                ('date_achat', models.DateField(default=django.utils.timezone.now)),
                ('cout_achat', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='entretien',
            name='voiture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voiture.Voiture'),
        ),
        migrations.AddField(
            model_name='consommation',
            name='voiture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voiture.Voiture'),
        ),
    ]
